project:
  type: website

website:
  title: "Chen Tang"
  favicon: "images/favicon.ico"
  google-analytics: "G-SJNBHSK0N5"
  navbar:
    title: "Chen Tang"
    logo: "images/logo_big.png"
    search: true
    right:
      - text: "Posts"
        href: index.qmd
      - text: "CV"
        file: cv.pdf
      - about.qmd
      - icon: twitter
        href: https://twitter.com/tngchn
      - icon: linkedin
        href: https://www.linkedin.com/in/tangchen/
  page-footer:
    left: "This blog is powered by [Quarto](https://quarto.org/). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: envelope
        href: mailto:tangc@tangc.net
      - icon: linkedin
        href: https://www.linkedin.com/in/tangchen/
      - icon: twitter
        href: https://twitter.com/tngchn
      - icon: github
        href: https://github.com/tangchen/

format:
  html:
    smooth-scroll: true
    theme: litera
    css: styles.css

editor: visual

comments:
  giscus:
    repo: tangchen/blog